name: Package and Release 
on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "donniedice"
          git config --global user.email "donniedice@protonmail.com"
          
      - name: Extract Version from TOC
        id: extract_version
        run: |
            version=$(grep -oP '^## Version: \K(.*)' ./*.toc)
            echo "::set-output name=version::$version"

      - name: Package and Release
        uses: BigWigsMods/packager@master

      - name: Parse Changelog
        id: parse_changelog
        run: |
          changelog=$(cat CHANGES.md)
          IFS=$'\n'
          for line in $changelog; do
            action=$(echo $line | cut -d '-' -f 1 | xargs)
            description=$(echo $line | cut -d '-' -f 2 | xargs)
            file=$(echo $line | cut -d '-' -f 3 | xargs | tr -d '[]')
            echo "Action: $action, Description: $description, File: $file"
          done
        shell: bash
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
